/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xF0, 0x89, 0x81, 0xE1, 0x83, 0xAB, 0x7C, 0x56}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }
#define VIALRGB_NO_DIRECT

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 120

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

// #define FLOW_TAP_TERM 150
// #define CAPS_WORD_IDLE_TIMEOUT 3000

#define PALETTEFX_ENABLE_ALL_EFFECTS
#define PALETTEFX_ENABLE_ALL_PALETTES
#define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE
