/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

//Vial Keyboard UID
#define VIAL_KEYBOARD_UID {0xF4, 0x6E, 0xF8, 0x3A, 0x5B, 0x50, 0xBC, 0x06}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }
#define VIALRGB_NO_DIRECT

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 120
#define HOLD_ON_OTHER_KEY_PRESS
// #define FLOW_TAP_TERM 150
// #define CAPS_WORD_IDLE_TIMEOUT 3000

#define PALETTEFX_ENABLE_ALL_EFFECTS
#define PALETTEFX_ENABLE_ALL_PALETTES
#define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE