/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xAF, 0x0F, 0x41, 0x84, 0x93, 0xA9, 0x2E, 0xC8}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
#define VIALRGB_NO_DIRECT

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 120

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

// #define FLOW_TAP_TERM 150
// #define CAPS_WORD_IDLE_TIMEOUT 3000

#define PALETTEFX_ENABLE_ALL_EFFECTS
#define PALETTEFX_ENABLE_ALL_PALETTES
#define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE
